#!/bin/env sh

BASEDIR=$(dirname "$0")

#rofi -theme-str 'window { width: 840; }' \
rofi  \
-kb-move-char-back "Control+b" \
-kb-move-char-forward "Control+f" \
-kb-custom-16 "Ctrl+equal" \
-kb-custom-17 "Alt+m" \
-kb-custom-18 "minus,underscore,Left" \
-kb-custom-19 "equal,plus,Right" \
-show rofi-sink-mixer \
-eh 3 \
-modi "rofi-sink-mixer:$BASEDIR/rofi-mixer.py --type sink,rofi-app-mixer:$BASEDIR/rofi-mixer.py --type app,rofi-source-mixer:$BASEDIR/rofi-mixer.py --type source" "$@"
